// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWIYtEQB5SSjflr1b7hWA3aE78nTGxYw',
    appId: '1:1097848812162:android:64cd17d45b33dd578b3a9b',
    messagingSenderId: '1097848812162',
    projectId: 'event-final2',
    storageBucket: 'event-final2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLfZBeRrbY5jX6TY3lnx0mlDaYLxO9eiw',
    appId: '1:1097848812162:ios:30f1375bad32de768b3a9b',
    messagingSenderId: '1097848812162',
    projectId: 'event-final2',
    storageBucket: 'event-final2.appspot.com',
    androidClientId: '1097848812162-iohggnhhdaiq9pscbk37aq8e360uqn17.apps.googleusercontent.com',
    iosClientId: '1097848812162-8a9rdjftc0j7od6ucg66iere52ndah2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventPlanning2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVq-NKqwvimq7yIQy2ovrBPC71Xn1wLyM',
    appId: '1:1097848812162:web:760cb3668cf011e58b3a9b',
    messagingSenderId: '1097848812162',
    projectId: 'event-final2',
    authDomain: 'event-final2.firebaseapp.com',
    storageBucket: 'event-final2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLfZBeRrbY5jX6TY3lnx0mlDaYLxO9eiw',
    appId: '1:1097848812162:ios:30f1375bad32de768b3a9b',
    messagingSenderId: '1097848812162',
    projectId: 'event-final2',
    storageBucket: 'event-final2.appspot.com',
    androidClientId: '1097848812162-iohggnhhdaiq9pscbk37aq8e360uqn17.apps.googleusercontent.com',
    iosClientId: '1097848812162-8a9rdjftc0j7od6ucg66iere52ndah2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventPlanning2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVq-NKqwvimq7yIQy2ovrBPC71Xn1wLyM',
    appId: '1:1097848812162:web:5385c461176c1da58b3a9b',
    messagingSenderId: '1097848812162',
    projectId: 'event-final2',
    authDomain: 'event-final2.firebaseapp.com',
    storageBucket: 'event-final2.appspot.com',
  );

}